# build stage
FROM golang:1.16 as builder

ENV GO111MODULE=on

WORKDIR /app

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build

# final stage
FROM scratch
COPY --from=builder /app/cleaner /app/
EXPOSE 33005
EXPOSE 7882
ENTRYPOINT ["/app/cleaner"]
